title: The Typology of Decision-Making Tasks
description: A website containing everything you need to know about the typology and many maaaany examples.
theme: just-the-docs

url: https://kamibrumi.github.io/typology

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
